#pragma once

#include "tui.hpp"
#include <string>

// Decode percent (url) encoding, needed for file paths extracted from epubs.
constexpr auto decodePercentEncoding(std::string& str) -> void {
  if (!str.contains('%')) {
    return;
  }

  findAndReplaceAll(str, "%20", " ");
  findAndReplaceAll(str, "%21", "!");
  findAndReplaceAll(str, "%22", "\"");
  findAndReplaceAll(str, "%23", "#");
  findAndReplaceAll(str, "%24", "$");
  findAndReplaceAll(str, "%25", "%");
  findAndReplaceAll(str, "%26", "&");
  findAndReplaceAll(str, "%27", "'");
  findAndReplaceAll(str, "%28", "(");
  findAndReplaceAll(str, "%29", ")");
  findAndReplaceAll(str, "%2A", "*");
  findAndReplaceAll(str, "%2B", "+");
  findAndReplaceAll(str, "%2C", ",");
  findAndReplaceAll(str, "%2F", "/");
  findAndReplaceAll(str, "%3A", ":");
  findAndReplaceAll(str, "%3B", ";");
  findAndReplaceAll(str, "%3C", "<");
  findAndReplaceAll(str, "%3D", "=");
  findAndReplaceAll(str, "%3E", ">");
  findAndReplaceAll(str, "%3F", "?");
  findAndReplaceAll(str, "%40", "@");
  findAndReplaceAll(str, "%5B", "[");
  findAndReplaceAll(str, "%5C", "\\");
  findAndReplaceAll(str, "%5D", "]");
  findAndReplaceAll(str, "%5E", "^");
  findAndReplaceAll(str, "%60", "`");
  findAndReplaceAll(str, "%7B", "{");
  findAndReplaceAll(str, "%7C", "|");
  findAndReplaceAll(str, "%7D", "}");
  findAndReplaceAll(str, "%7E", "~");
  findAndReplaceAll(str, "%A2", "¢");
  findAndReplaceAll(str, "%A3", "£");
  findAndReplaceAll(str, "%A5", "¥");
  findAndReplaceAll(str, "%A6", "|");
  findAndReplaceAll(str, "%A7", "§");
  findAndReplaceAll(str, "%AB", "«");
  findAndReplaceAll(str, "%AC", "¬");
  findAndReplaceAll(str, "%AD", "¯");
  findAndReplaceAll(str, "%B0", "º");
  findAndReplaceAll(str, "%B1", "±");
  findAndReplaceAll(str, "%B2", "ª");
  findAndReplaceAll(str, "%B4", ",");
  findAndReplaceAll(str, "%B5", "µ");
  findAndReplaceAll(str, "%BB", "»");
  findAndReplaceAll(str, "%BC", "¼");
  findAndReplaceAll(str, "%BD", "½");
  findAndReplaceAll(str, "%BF", "¿");
  findAndReplaceAll(str, "%C0", "À");
  findAndReplaceAll(str, "%C1", "Á");
  findAndReplaceAll(str, "%C2", "Â");
  findAndReplaceAll(str, "%C3", "Ã");
  findAndReplaceAll(str, "%C4", "Ä");
  findAndReplaceAll(str, "%C5", "Å");
  findAndReplaceAll(str, "%C6", "Æ");
  findAndReplaceAll(str, "%C7", "Ç");
  findAndReplaceAll(str, "%C8", "È");
  findAndReplaceAll(str, "%C9", "É");
  findAndReplaceAll(str, "%CA", "Ê");
  findAndReplaceAll(str, "%CB", "Ë");
  findAndReplaceAll(str, "%CC", "Ì");
  findAndReplaceAll(str, "%CD", "Í");
  findAndReplaceAll(str, "%CE", "Î");
  findAndReplaceAll(str, "%CF", "Ï");
  findAndReplaceAll(str, "%D0", "Ð");
  findAndReplaceAll(str, "%D1", "Ñ");
  findAndReplaceAll(str, "%D2", "Ò");
  findAndReplaceAll(str, "%D3", "Ó");
  findAndReplaceAll(str, "%D4", "Ô");
  findAndReplaceAll(str, "%D5", "Õ");
  findAndReplaceAll(str, "%D6", "Ö");
  findAndReplaceAll(str, "%D8", "Ø");
  findAndReplaceAll(str, "%D9", "Ù");
  findAndReplaceAll(str, "%DA", "Ú");
  findAndReplaceAll(str, "%DB", "Û");
  findAndReplaceAll(str, "%DC", "Ü");
  findAndReplaceAll(str, "%DD", "Ý");
  findAndReplaceAll(str, "%DE", "Þ");
  findAndReplaceAll(str, "%DF", "ß");
  findAndReplaceAll(str, "%E0", "à");
  findAndReplaceAll(str, "%E1", "á");
  findAndReplaceAll(str, "%E2", "â");
  findAndReplaceAll(str, "%E3", "ã");
  findAndReplaceAll(str, "%E4", "ä");
  findAndReplaceAll(str, "%E5", "å");
  findAndReplaceAll(str, "%E6", "æ");
  findAndReplaceAll(str, "%E7", "ç");
  findAndReplaceAll(str, "%E8", "è");
  findAndReplaceAll(str, "%E9", "é");
  findAndReplaceAll(str, "%EA", "ê");
  findAndReplaceAll(str, "%EB", "ë");
  findAndReplaceAll(str, "%EC", "ì");
  findAndReplaceAll(str, "%ED", "í");
  findAndReplaceAll(str, "%EE", "î");
  findAndReplaceAll(str, "%EF", "ï");
  findAndReplaceAll(str, "%F0", "ð");
  findAndReplaceAll(str, "%F1", "ñ");
  findAndReplaceAll(str, "%F2", "ò");
  findAndReplaceAll(str, "%F3", "ó");
  findAndReplaceAll(str, "%F4", "ô");
  findAndReplaceAll(str, "%F5", "õ");
  findAndReplaceAll(str, "%F6", "ö");
  findAndReplaceAll(str, "%F7", "÷");
  findAndReplaceAll(str, "%F8", "ø");
  findAndReplaceAll(str, "%F9", "ù");
  findAndReplaceAll(str, "%FA", "ú");
  findAndReplaceAll(str, "%FB", "û");
  findAndReplaceAll(str, "%FC", "ü");
  findAndReplaceAll(str, "%FD", "ý");
  findAndReplaceAll(str, "%FE", "þ");
  findAndReplaceAll(str, "%FF", "ÿ");
}
